### ISSUE TITLE
Trailing commas in Windows

### ISSUE THREAD

**Issue by drwatsoncode** [shagabutdinov/sublime-status-message#1]
In Sublime Text 2 (v2.0.2) on Windows OS, I'm getting the following error:
`Error trying to parse file: Trailing comma before closing bracket in ...\Packages\StatusMessage\Default (Windows).sublime-keymap:7:5`

This is due to (several) trailing commas in the file **Default (Windows).sublime-keymap**, which should be removed. (e.g. on lines 6, 14, 15).

**Comment by shagabutdinov** [comment]
This is ST2 issue, probably it will be better for you to upgrade to ST3. I'm not closing ST2 issues but I'll join your pull request if you'll do it.
