### ISSUE TITLE
ToggleDefaultStatus isn't working (build 3114)

### ISSUE THREAD

**Issue by pinaworks** [shagabutdinov/sublime-status-message#2]
For a few Sublime Text updates now, the ToggleDefaultStatus command hasn't been working, and the ', Line x, Column y' can be seen at all times on the status bar. Is there any workaround
through that?

![wtlzen8](https://cloud.githubusercontent.com/assets/22161026/18457487/3b5c20b0-7927-11e6-8a00-b7b662a78b55.jpg)

**Comment by shagabutdinov** [comment]
May you try to replace `\0` to `\n` in https://github.com/shagabutdinov/sublime-status-message/blob/master/status_message.py#L58 ? 

I'm using latest version of sublime (build 3126) on Linux and I don't see this bug...

**Comment by pinaworks** [comment]
I just did it, but now instead of shifting ', Line x, Column y' slightly to the left and right, ToggleDefaultStatus does nothing. 

I've tried this with a few builds, including the current, and using both win 7 and 10

**Comment by pinaworks** [comment]
While messing with [ https://github.com/shagabutdinov/sublime-status-message/blob/master/status_message.py#L58 ](url), I found out that the ToggleDefaultStatus command _does_ work with whatever is in there instead of `\0`. I mean, the command is working, but whatever it works on, it's not the ', Line x, Column y'.

![untitled-1 copy](https://cloud.githubusercontent.com/assets/22161026/18934306/f4fc566c-85a6-11e6-9a71-558ed034837a.jpg)

**Comment by shagabutdinov** [comment]
This is differences of sublime behaviour for Linux, Windows and MacOS... The `\0` hack was used to hide the rest of string but seems it does not work anymore for you OS/version. 

I don't have ideas how to hide default status message. Maybe you may try to insert several thousands of spaces instead of `example` but I'm not sure it'll help.

**Comment by pinaworks** [comment]
well, inserting spaces _did_ work, except it also bumped tab/space size and file type out of the status bar

**Comment by shagabutdinov** [comment]
I don't know how to help you... there are only three probable variants could work (`\n`, `\0` and spaces) and they all don't work; sorry :(

**Comment by pinaworks** [comment]
it's okay, at least spaces helps with it. I really enjoy SublimeStatusMessage, so I wouldn't like to stop using it. I'll try and see if I can get people who use windows and if they know a workaround for this. thanks for helping, nonetheless :)

**Comment by shagabutdinov** [comment]
Sure, no problem; I glad you like my plugin :)) I close this issue for now but let me know if you'll find a workaround, I'll include it repository.
